### ISSUE TITLE
[QUESTION] How to add new projectile type?

### ISSUE THREAD

**Issue by Porama6400** [Shampaggon/CrackShot#13]
How can i add custom projectile type?

Example , if i want to add laser projectile type and i want config look like this

Lasergun:
    Item_Information:
        Item_Name: "&fLaser gun"
        Item_Type: 280
    Shooting:
        Cancel_Left_Click_Block_Damage: true
        Cancel_Right_Click_Interactions: true
        Delay_Between_Shots: 20
        Projectile_Type: laser
        Projectile_Damage: 5
    Laser:
        R: 255
        G: 0
        B: 0

How can i do it?

**Comment by Porama6400** [comment]
NO ONE WILL ANSWER ME HERE , BYE

**Comment by OfficialJonesy** [comment]
Your answer is you cant
